version: 0.2

env:
  variables:
    STAGE: "dev"
    IDEAS_TABLE_READ_CAPACITY: 2
    IDEAS_TABLE_WRITE_CAPACITY: 2
  parameter-store:
    IDEAS_TABLE_NAME: /iideass/dev/be/IDEAS_TABLE_NAME
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm ci
      - npx sls --version
  build:
    commands:
      - echo "Running tests (SKIPPED FOR NOW)"
      # - npm run test
  post_build:
    commands:
      - echo "Deploying to dev environment"
      - npm run deploy
